<?php

namespace elfib\CommercialBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FournisseursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseursRepository extends EntityRepository
{
  public function getAll()
  {
    
  }
}
