parameters:
#    elfib_user.example.class: elfib\UserBundle\Example

services:
#    elfib_user.example:
#        class: %elfib_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
