<?php

namespace elfib\MouvementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * commandeMPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commandeMPRepository extends EntityRepository
{
}
