<?php

namespace elfib\MouvementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * livraisonMPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class livraisonMPRepository extends EntityRepository
{
}
