<?php

namespace elfib\StockBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmplacementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmplacementsRepository extends EntityRepository
{
  public function getForFabrication($nomenclature)
  {
    $queryBuilder = $this->createQueryBuilder('emp')
      ->where('matierePremiere_id = ?', $nomenclature->getId())
      ->orderBy('');
    
    $query = $queryBuilder->getQuery();
    
    $resultats = $query->getResult();

    return $resultats;
  }
}
