<?php

namespace elfib\StockBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmplacementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmplacementsRepository extends EntityRepository
{
}
