<?php

namespace elfib\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatierePremiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatierePremiereRepository extends EntityRepository
{
}
