<?php

namespace elfib\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitFiniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitFiniRepository extends EntityRepository
{
}
