elfib_nomenclature_homepage:
    pattern:  /article
    defaults: { _controller: elfibArticleBundle:Nomenclature:index }


#
# Nomenclatures
#
elfib_nomenclature_voir:
    pattern:  /article/{id}
    defaults: { _controller: elfibArticleBundle:Nomenclature:voir }
    requirements:
      id: \d+

elfib_nomenclature_ajout_produit_fini:
    pattern:  /article/ajout/produit_fini
    defaults: { _controller: elfibArticleBundle:Nomenclature:ajoutPF }

elfib_nomenclature_ajout_matiere_premiere:
    pattern:  /article/ajout/matiere_premiere
    defaults: { _controller: elfibArticleBundle:Nomenclature:ajoutMP }

elfib_nomenclature_modifier:
    pattern:  /article/modifier/{id}
    defaults: { _controller: elfibArticleBundle:Nomenclature:modifier }
    requirements:
      id: \d+

elfib_nomenclature_desactiver:
    pattern:  /article/desactiver/{id}
    defaults: { _controller: elfibArticleBundle:Nomenclature:desactiver }
    requirements:
      id: \d+

elfib_nomenclature_activer:
    pattern:  /article/activer/{id}
    defaults: { _controller: elfibArticleBundle:Nomenclature:activer }
    requirements:
      id: \d+

